CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    plan_id INT UNSIGNED NOT NULL,
    storage_limit_bytes BIGINT UNSIGNED NOT NULL,
    storage_used_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    bandwidth_limit_bytes BIGINT UNSIGNED NOT NULL,
    bandwidth_used_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    bandwidth_reset_month INT UNSIGNED NOT NULL,
    status ENUM('active', 'suspended', 'deleted') DEFAULT 'active',
    suspended_reason TEXT NULL,
    suspended_at TIMESTAMP NULL,
    last_login_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_plan_id (plan_id),
    INDEX idx_status (status),
    INDEX idx_email (email),
    INDEX idx_username (username),
    INDEX idx_uuid (uuid),
    FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE RESTRICT
);